name: hugo deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Install
        run: make install
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4 
        with:
          pin-name: 'updocs'
          path: './public'
          pinata-api-key: ${{ secrets.PINATAAPIKEY }}
          pinata-secret-api-key: ${{ secrets.PINATASECRETAPIKEY }}
          verbose: true
          remove-old: true
        id: deploy
      - name: Mail
        run: 'printf  "From: noreply@unifiedpush.org\nTo: deploy@unifiedpush.org\nSubject: Build was completed\n\nhttps://ipfs.io/ipfs/${{ steps.deploy.outputs.HASH }}/\n" > mail.txt ; curl --ssl-reqd --url "smtps://mail.gandi.net:465" --user "noreply@unifiedpush.org:${{ secrets.MAILPASS }}" --mail-from "noreply@unifiedpush.org" --mail-rcpt "deploy@unifiedpush.org" --upload-file mail.txt'
