name: hugo deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4 
        with:
          pin-name: 'updocs'
          path: './public'
          pinata-api-key: ${{ secrets.PINATAAPIKEY }}
          pinata-secret-api-key: ${{ secrets.PINATASECRETAPIKEY }}
          verbose: true
          remove-old: true
        id: deploy
      - name: Gotify Notification
        uses: eikendev/gotify-action@master
        with:
          gotify_api_base: '${{ secrets.gotify_api_base }}' #without /message
          gotify_app_token: '${{ secrets.gotify_app_token }}'
          notification_title: 'UP Docs Website Deploy Complete'
          notification_message: "Your build was completed. Hash: ${{ steps.deploy.outputs.HASH }}" 
