name: hugo deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Update Spec"]
    types:
      - completed


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          lfs: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Install
        run: make install
      - name: Build
        run: hugo --minify
      - name: deploy-upload
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4 
        with:
          username: 'ubuntu'
          server: 'unifiedpush.org'
          ssh_private_key: ${{ secrets.SSHKEY }}
          local_path: './public/*'
          remote_path: '/tmp/action-sftp-upload'
          delete_remote_files: true
          sftpArgs: '-o ConnectTimeout=5'
      - name: Deploy
         # private key left over by sftp action
        run: |
          HASH=$(ssh -o StrictHostKeyChecking=no -i ../private_key.pem ubuntu@unifiedpush.org sudo -u ipfs ipfs add --recursive --pin=false --quieter /tmp/action-sftp-upload)
          echo "::set-output name=HASH::$HASH"
        id: deploy
      - name: DNSLINK
        run: 'curl -D- -X PUT -H "Content-Type: application/json" -H "Authorization: Apikey ${{ secrets.GandiAPI }}" -d "{\"rrset_ttl\": 300,\"rrset_values\": [\"dnslink=/ipfs/${{ steps.deploy.outputs.HASH }}\"]}" https://api.gandi.net/v5/livedns/domains/unifiedpush.org/records/_dnslink/TXT'
